/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as piggyBankSol from "./piggyBank.sol";
export type { piggyBankSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { PiggyBank } from "./piggyBank.sol/PiggyBank";
export { PiggyBank__factory } from "./factories/piggyBank.sol/PiggyBank__factory";
