/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ballotSol from "./Ballot .sol";
export type { ballotSol };
export type { Ballot } from "./Ballot";
export * as factories from "./factories";
export type { Ballot } from "./Ballot .sol/Ballot";
export { Ballot__factory } from "./factories/Ballot .sol/Ballot__factory";
