/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustomERC20 } from "./CustomERC20";
export * as factories from "./factories";
export { CustomERC20__factory } from "./factories/CustomERC20__factory";
