/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as schoolmanagementSol from "./schoolmanagement.sol";
export type { schoolmanagementSol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { SchoolManagement } from "./schoolmanagement.sol/SchoolManagement";
export { SchoolManagement__factory } from "./factories/schoolmanagement.sol/SchoolManagement__factory";
