/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20Sol from "./ERC20.sol";
export type { erc20Sol };
import type * as erc721Sol from "./ERC721.sol";
export type { erc721Sol };
import type * as piggyBankSol from "./piggyBank.sol";
export type { piggyBankSol };
