/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export * as erc721Sol from "./ERC721.sol";
export * as piggyBankSol from "./piggyBank.sol";
